name = "Aeronautics V2"
author = "Callum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a7df901e5b6eaf9becdc546091261d368952a1949cf5ce63c8752b8459c1205"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
