name = "Aeronautics V2"
author = "Callum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19748ea398ce6e3b33aeaf12f1ca51aa099f000f127b5414f15c4c59f95e46af"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
