name = "Aeronautics V2"
author = "Callum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e1961dace8dca1995c749bc505bb2439da3cd18463ca86ebcdd90db749e2eb1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
